AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'bin/*'
  TargetRubyVersion: 2.6.3

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/LineLength:
  Max: 112  # Maximum line length from `rails new`

Metrics/MethodLength:
  Max: 15

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
